//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Editor.rc
//
#define IDS_EDIT_STATE                  1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FORMVIEW                    101
#define IDD_RENDER_WND                  101
#define IDS_RIBBON_MAIN                 101
#define IDC_CUR_EDIT_SELECT             104
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_STATUS_PANE3                126
#define IDS_STATUS_PANE4                127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_EditorTYPE                  130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define ID_PARTICLE_LIST_PANEL          310
#define ID_RESPANEL_MATERIAL            311
#define IDC_CUR_EDIT_MOVE               312
#define ID_RESPANEL_TEXTURE             312
#define IDC_CUR_EDIT_ROTATE             313
#define ID_RESPANEL_PARTICLESYSTEM      313
#define IDC_CURSOR_EDIT_SCALE           314
#define ID_RESPANEL_MESH                314
#define IDC_LIST_PARTICLES              315
#define IDD_DIALOG_OBJECTS              316
#define ID_MODELEDITOR_PANEL            316
#define ID_MODELEDITOR_PROPGRID         317
#define IDR_MENU1                       318
#define IDR_MENU_PARTICLE               318
#define ID_PARTICLEEDITOR_PROPGRID      318
#define IDR_TOOLBAR_PARTICLE_EDITOR     319
#define ID_MODELEDITOR_INFOPANEL        319
#define ID_MODELEDITOR_TIMELINE_PANEL   320
#define ID_BTN_TIMELINE_PLAY            321
#define IDC_CUR_EDIT_MOVE_X             322
#define ID_BTN_TIMELINE_STOP            322
#define IDC_CUR_EDIT_MOVE_Y             323
#define ID_BTN_TIMELINE_PAUSE           323
#define IDC_CUR_EDIT_MOVE_Z             324
#define ID_BTN_TIMELINE_TOBEGIN         324
#define IDC_CUR_EDIT_ROTATE_X           325
#define ID_BTN_TIMELINE_TOEND           325
#define IDC_CUR_EDIT_ROTATE_Y           326
#define IDR_MENU_CAMERA_SPEED           326
#define ID_MODIFY_CAM_PROP              326
#define IDC_CUR_EDIT_ROTATE_Z           327
#define IDRIB_SKYBOX_PROP               327
#define IDI_ICON1                       328
#define IDRIB_SCENE_PROP                328
#define IDR_PARTICLE_WND                329
#define IDRIB_MAINLIGHT_PROP            329
#define IDRIB_EDITORCFG_PROP            330
#define IDD_DIALOG_NEW_MAP              331
#define IDRIB_MOVE_CLAMP_TERRAIN        331
#define IDB_BITMAP1                     332
#define IDB_BITMAP_ERROR                332
#define IDRIB_MOVE_ALIGN_NORMAL         332
#define IDRIB_MOVE_SNAP_GRID            333
#define IDRIB_MOVECAM_CLAMP_TERRAIN     334
#define IDR_MENU2                       344
#define IDR_POPUP_MESHEDIT              344
#define IDB_BTN_PLAY                    345
#define IDB_BTN_STOP                    346
#define IDB_BTN_PAUSE                   347
#define IDB_BTN_TOBEGIN                 348
#define IDB_BTN_TOEND                   349
#define IDB_TOOLBAR_MAIN                357
#define IDD_DIALOG_OPENMAP              358
#define IDI_ICON_PROP                   359
#define IDI_ICON_CAMSPEED_FAST          360
#define IDI_ICON_CAMSPEED_NORMAL        361
#define IDI_ICON_CAMSPEED_SLOW          362
#define IDB_BITMAP_CAMERA_SPEED         363
#define IDD_DIALOG_SPLASH               364
#define IDB_BITMAP2                     365
#define IDB_BITMAP_SPLASH               365
#define IDC_TREE_OBJECTS                1003
#define IDC_COMBO1                      1005
#define IDC_EDIT_MAP_WIDTH              1007
#define IDC_EDIT_MAP_HEIGHT             1008
#define IDC_EDIT_WORLD_SIZE             1008
#define IDC_EDIT_MAP_NAME               1009
#define IDC_EDIT_UNIT_SCALE             1010
#define IDC_EDIT_TERRAIN_CNT_X          1010
#define IDC_LIST_PARTICLE_SYSTEM_LIST   1011
#define IDC_EDIT_TERRAIN_CNT_Z          1011
#define IDC_LIST_MAPLIST                1012
#define IDC_EDIT_TEXTURE_WORLD_SIZE     1012
#define IDC_EDIT_COLOURMAP_SIZE         1013
#define IDC_CHECK_CAST_DYN_SHADOWS      1014
#define IDC_EDIT_LIGHTMAP_SIZE          1015
#define IDC_EDIT_BLENDMAP_SIZE          1016
#define IDC_EDIT_COLOURMAP_DISTANCE     1017
#define IDC_EDIT_COMPOSITEMAP_DISTANCE  1017
#define IDC_EDIT_COMPOSITEMAP_SIZE      1018
#define IDC_EDIT_MAX_PIXEL_ERROR        1019
#define IDC_EDIT_SKIRT_SIZE             1020
#define ID_VP_MAX                       32771
#define ID_VP_1x2                       32772
#define ID_VP_2x2                       32773
#define ID_SCENE_SKY_BOX                32774
#define ID_SCENE_ENVIRONMENT            32775
#define ID_VIEW_SCENE_GRAPH             32776
#define ID_REDO                         32778
#define ID_EDIT_MOVE                    32783
#define ID_EDIT_ROTATE                  32784
#define ID_EDIT_SCALE                   32785
#define ID_SHOW_RES_MANAGER             32786
#define ID_SHOW_BOUDNING_BOX            32787
#define ID_SHOW_WIRE                    32794
#define ID_CLAMP_ON_TERRAIN             32795
#define ID_SCENE_TERRAIN                32797
#define ID_SCENE_UPDATE_TERRAIN         32799
#define ID_ALIGN_TERRAIN_NORMAL         32800
#define ID_SHOW_OBJECTS                 32801
#define ID_APPLY_CAMERA                 32804
#define ID_CURRENT_CAMERA               32805
#define ID_MATERIAL_SCHEME              32806
#define ID_VIEW_SELECT_CAMERA           32807
#define ID_COMPOSITOR                   32808
#define IDC_SNAPSHOT_MINIMAP            32810
#define IDM_PARTICLE_SAVE               32813
#define IDM_PARTICLE_OPEN               32814
#define ID_TOOLS_PARTICLEEDITOR         32816
#define ID_NEW_PARTICLE                 32817
#define ID_ADD_EMITTER                  32818
#define ID_DELETE_EMITTER               32819
#define ID_ADD_AFFECTOR                 32820
#define ID_REMOVE_AFFECTOR              32821
#define ID_EDIT_PARTICLE_ATTR           32822
#define ID_EDIT_AFFECTOR_ATTR           32823
#define ID_EDIT_EMITTER_ATTR            32824
#define ID_SAVE_PARTICLE                32825
#define ID_DELETE_PARTICLE              32827
#define ID_MATERIAL_DLG                 32828
#define ID_PARTICLE_OPTION              32829
#define ID_CAMERA_SPEED                 32830
#define ID_PICK_FILTER                  32831
#define ID_CAMERASPEED_SLOW             32832
#define ID_CAMERASPEED_NORMAL           32833
#define ID_CAMERASPEED_FAST             32834
#define ID_SAVE_ALL_PARTICLE            32835
#define ID_EDIT_PARTICLE_RENDER         32841
#define ID_SHOW_WIREFRAME               32842
#define ID_SNAP_CONFIG                  32843
#define ID_SNAP_ANGLED                  32844
#define ID_32845                        32845
#define ID_SHOW_MODEL_EDITOR            32846
#define ID_32847                        32847
#define ID_32848                        32848
#define ID_32849                        32849
#define ID_32850                        32850
#define ID_MODEL_EDITOR_SAVE            32854
#define ID_MODEL_EDITOR_SAVEAS          32855
#define ID_MODEL_EDITOR_DELETE          32856
#define ID_MODEL_EDITOR_OPTIONS         32857
#define ID_MODEL_EDITOR_BUILD_EDGELIST  32859
#define ID_MESHEDIT_IMPORTANIMATION     32873
#define ID_MESHEDIT_DELETEANIMATION     32874
#define ID_BUTTON32879                  32879
#define ID_MATERIAL_OPEN                32882
#define ID_MATERIAL_EDITOR_OPEN         32883
#define ID_32884                        32884
#define ID_TOOLS_MATERIAL_EDITOR        32885
#define ID_PARTICLE_VIEW_COMPOSITOR     32886
#define ID_BUTTON32887                  32887
#define ID_MESHEDIT_ADDLINKEDSKELETON   32889
#define ID_PARTICLE_EDITOR_CAPTURE      32893
#define ID_EDITSTATE_SELECT             52779
#define ID_EDITSTATE_CREATE             52780
#define ID_EDITSTATE_TERRAIN            52781
#define ID_EDITSTATE_TERRAIN_SURFACE    52782
#define ID_EDITSTATE_TERRAIN_PATH_FINDER 52783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        366
#define _APS_NEXT_COMMAND_VALUE         32901
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           337
#endif
#endif
