#include "stdafx.h"
#include "CinemaEditorEvents.h"

IMPL_PARTICLE_EVENT(NewCinema)
IMPL_PARTICLE_EVENT(SaveAll)
IMPL_PARTICLE_EVENT(AddTrack)
IMPL_PARTICLE_EVENT(RemoveTrack)
IMPL_PARTICLE_EVENT(EditCinema)
IMPL_PARTICLE_EVENT(CreateKeyFrame)

IMPL_PARTICLE_EVENT(ShowCinemaPropObject)
IMPL_PARTICLE_EVENT(ClearCinemaPropObject)

IMPL_PARTICLE_EVENT(Play)
IMPL_PARTICLE_EVENT(Pause)
IMPL_PARTICLE_EVENT(Stop)
IMPL_PARTICLE_EVENT(ToBegin)
IMPL_PARTICLE_EVENT(ToEnd)

IMPL_PARTICLE_EVENT(UpdateUI_CinemaList)
IMPL_PARTICLE_EVENT(UpdateUI_CinemaCtrl)
IMPL_PARTICLE_EVENT(UpdateUI_AddTrack)
IMPL_PARTICLE_EVENT(UpdateUI_RemoveTrack)
IMPL_PARTICLE_EVENT(UpdateUI_CreateKeyFrame)